version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
      - "8080:8080"
    environment:
      - SERVICES=sqs

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"